---
k3s_systemd_dir: /etc/systemd/system
k3s_master_ip: "{{ hostvars[groups['master'][0]]['ansible_host'] | default(groups['master'][0]) }}"

k3s_token: "{{ hostvars[groups['master'][0]]['token'] }}"
