version: '3'
services:
  server:
    image: rancher/k3s:v0.1.0-rc8
    command: server
    environment:
    - K3S_CLUSTER_SECRET=somethingtotallyrandom
    volumes:
    - config:/etc/rancher/k3s
    tmpfs:
    - /run
    - /var/run
    privileged: true

  node:
    image: rancher/k3s:v0.1.0-rc8
    tmpfs:
    - /run
    - /var/run
    privileged: true
    environment:
    - K3S_URL=https://server:6443
    - K3S_CLUSTER_SECRET=somethingtotallyrandom

  sonobuoy:
    build: .
    volumes:
    - config:/etc/rancher/k3s

volumes:
  config: {}
