k3s_version: v0.8.1
ansible_user: debian
k3s_systemd_dir: /etc/systemd/system
k3s_master_ip: "{{ hostvars[groups['master'][0]]['ansible_host'] | default(groups['master'][0]) }}"
k3s_extra_server_args: ""
